### ISSUE TITLE
Check splitting out of python lesson

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/python-ecology-lesson#1]
@wrightaprilm & @tracykteal - could you take a look at this and see if I've extracted the files and history of the Python lessons successfully. Thanks.

**Comment by wrightaprilm** [comment]
This looks accurate per my contributions.

**Comment by tracykteal** [comment]
Files and history look good to me. Thanks!

**Comment by qjcg** [comment]
Seems like all concerned are in agreement here; closing this issue.
