### ISSUE TITLE
05-loops-and-functions.md contains confusing text explanations

### ISSUE THREAD

**Issue by weiapplele** [datacarpentry/python-ecology-lesson#122]
1.  "If a local variable has the same name as a variable somewhere else in the code, the local variable hides but doesn't overwrite the other."
-- "a variable somewhere else in the code" means global variables or local variables in other functions?

2.  "The line defining the loop must start with `for`" 
-- in python, we can also define while loops, a better way: "Here, the line defining the loop start with `for`"

3.  "Functions are reusable, self-contained pieces of code that are called with a single command."
-- a better way: "Functions are reusable, self-contained pieces of code that can be called with a single command. "

**Comment by wrightaprilm** [comment]
Great! Would you like to open a pull request with the changes, or would you like me to do it? I noticed that this has an instructor training tag, which means you have to, I think, but I'm happy to help you do that.

**Comment by weiapplele** [comment]
Hey, April,

Thanks for getting back to me. I can create a pull request!

**Comment by wrightaprilm** [comment]
Great. Just so you're aware, we are publishing a new edition of the lessons on Jan. 6. If you're able to make the pull request before then, this will be in. If not, that's fine, too.

**Comment by willingc** [comment]
I'll take a look at this issue.

**Comment by qjcg** [comment]
I think this issue was followed up with #142 . Some changes have been requested, but nothing merged yet.

**Comment by willingc** [comment]
Thanks @qjcg. Good catch. I'll move on to another issue :cake:

**Comment by qjcg** [comment]
Sounds good @willingc . In fact, I think we can go ahead and close this issue, since the changes to be addressed are being discussed in #142.
