### ISSUE TITLE
Update the front page

### ISSUE THREAD

**Issue by djinnome** [datacarpentry/python-ecology-lesson#123]
The [front page](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/index.md) has a broken link to the [deprecated matplotlib](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/06-plotting-with-matplotlib) lesson.  Update link to [new ggplot lesson](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/06-visualization-ggplot-python.md).

**Comment by djinnome** [comment]
Actually, the autogenerate [html version of the new ggplot lesson](http://www.datacarpentry.org/python-ecology-lesson/06-visualization-ggplot-python.html) looks terrible.

**Comment by wrightaprilm** [comment]
Hahaha, jeez. This I might actually take a peek at after my kid goes to bed tonight. That's remarkably awful.

**Comment by tracykteal** [comment]
We're having a somewhat related conversation in the R-ecology repo about a 'dev' branch where we can see formatting before it goes live.

https://github.com/datacarpentry/R-ecology-lesson/issues/154

Agree this is a priority to fix. I've been working on templating on some other lessons today, so I'll see if I can put in a PR.

**Comment by ctb** [comment]
See #124.

**Comment by mkuzak** [comment]
The matplotlib lesson link have been removed and ggplot lesson link updated. I think we can close this one @djinnome
