### ISSUE TITLE
Broken Link: Setup link

### ISSUE THREAD

**Issue by iaine** [datacarpentry/python-ecology-lesson#136]
In the[ Schedule](http://www.datacarpentry.org/python-ecology-lesson/#schedule) section, the set up link is broken and returns a 404 page. This appears to be a generic part of the template from a Data Carpentry. As the set up information is above the schedule, can this link be removed or retargeted to the[ appropriate name anchor](http://www.datacarpentry.org/python-ecology-lesson/#setting-up-python)?  I willing to try and fix as part of DC trainer checkout.

**Comment by qjcg** [comment]
Hello, thanks for this! This has now been [fixed](https://github.com/datacarpentry/python-ecology-lesson/commit/f5478cde5cfdf7f245a5ee1358b1ceace9837816), so closing this issue.
