### ISSUE TITLE
Add timing estimates to each episode

### ISSUE THREAD

**Issue by qjcg** [datacarpentry/python-ecology-lesson#138]

**Comment by tracykteal** [comment]
Also related to the schedule in https://github.com/datacarpentry/python-ecology-lesson/issues/91

Adding timing will create a schedule.

**Comment by tmorrell** [comment]
I'm teaching this lesson next week and will provide my timing as a starting point.

**Comment by tracykteal** [comment]
Great, thank you! That will be really helpful.

**Comment by tracykteal** [comment]
Any other feedback would be welcome too. We won't change things too much before release next week, but if things could be reordered, expanded or reduced, we can take that on after the release for the next version.

**Comment by tmorrell** [comment]
Will do!

**Comment by tracykteal** [comment]
I added initial estimates reading through the lessons.

https://github.com/datacarpentry/python-ecology-lesson/pull/183

 It will be good to know how that matches with teaching time. Also, from just these estimates, it looks like there's too much to teach in one day (a morning session + an afternoon session). I'll create another issue where we can discuss if there's too much to teach, and if so, what are people leaving out.

**Comment by qjcg** [comment]
Closed by #183.
