### ISSUE TITLE
Bug BBQ: Add key points to each episode

### ISSUE THREAD

**Issue by qjcg** [datacarpentry/python-ecology-lesson#139]

**Comment by tracykteal** [comment]
This is important, but also needs to be done by someone who has a good understanding of each episode. Since the questions and objectives are already listed, I'm going to make this a post lesson release update. We should make sure to come back to it.

**Comment by alex-pakalniskis** [comment]
I checked the episodes and they all contain key points: https://datacarpentry.org/python-ecology-lesson/

Closing since it is actually complete. 

Thanks for your contributions.
