### ISSUE TITLE
Check input and output filenames and paths

### ISSUE THREAD

**Issue by wrightaprilm** [datacarpentry/python-ecology-lesson#148]
Bug BBQ:

Check paths and names of files used as input and that learners are directed appropriately to output paths and files. 

**Level:** Beginner.

Thank you for filing an issue! 

These lessons are being prepared for publication. From March 15, 2017 to April 21, 2017 issues related to [lesson release preparations](https://github.com/datacarpentry/lesson-release/blob/master/release-checklist.md) are particularly appreciated.

**Comment by tracykteal** [comment]
For this issue, someone should run the code in the lesson to make sure the paths work.

**Comment by wrightaprilm** [comment]
I think I have caught all the I/O issues.
