### ISSUE TITLE
Instructors guide

### ISSUE THREAD

**Issue by wrightaprilm** [datacarpentry/python-ecology-lesson#149]
- [x] Add info on the jupyter NB
- [x] Check for currency with 
     - [x] names (variables, vectors, etc)
    - [x] file i/o paths

Thank you for filing an issue! 

These lessons are being prepared for publication. From March 15, 2017 to April 21, 2017 issues related to [lesson release preparations](https://github.com/datacarpentry/lesson-release/blob/master/release-checklist.md) are particularly appreciated.

**Comment by wrightaprilm** [comment]
Looks fine for now, but will leave open pending further exercise changes.

**Comment by orchid00** [comment]
hi @wrightaprilm 

I found little typos on the guide, section Checking installations
it should refer to  `_includes/scripts`
