### ISSUE TITLE
Jupyter setup instructions

### ISSUE THREAD

**Issue by tmorrell** [datacarpentry/python-ecology-lesson#150]
Include basis instructions for setting up a new Jupyter notebook in setup.md or modify the beginning of lesson 00 to introduce the very basics of working in a jupyter notebook.  At the moment there is a bit of a gap between the end of setup and the beginning of lesson 00

Perhaps get inspiration from https://github.com/swcarpentry/python-novice-gapminder/blob/gh-pages/_episodes/01-run-quit.md

May be related to issue #10

**Comment by willingc** [comment]
I'll send a PR for this one.
