### ISSUE TITLE
dataframe.describe() bug

### ISSUE THREAD

**Issue by tmorrell** [datacarpentry/python-ecology-lesson#153]
Add to instructors notes that pandas .18.1 (and maybe others) has a bug where 

surveys_df['weight'].describe() in lesson 01 returns

RuntimeWarning: Invalid value encountered in percentile
count    32283.000000
mean        42.672428
std         36.631259
min          4.000000
25%               NaN
50%               NaN
75%               NaN
max        280.000000

because of the Nan values in the file.  This is fixed in pandas .18.2 https://github.com/pandas-dev/pandas/issues/13476

**Comment by wrightaprilm** [comment]
Fixed with c4c7515.
