### ISSUE TITLE
dataFrame methods or attributes?

### ISSUE THREAD

**Issue by proccaserra** [datacarpentry/python-ecology-lesson#154]
In https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/_episodes/01-starting-with-data.md

in section "Useful Ways to View DataFrame objects in Python", the material refers to 'dataFrame methods' to identify calls allowing to obtain properties/information on a dataframe, such as 'tail', 'head', 'size'. However Pandas documentation [http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html] refers to some of these elements as 'attributes'.
so { 'size', 'dtypes', 'shape'} are attributes while {'head', 'tail' , 'unique'} are methods.

Also 'columns' is referred to as a 'parameter' for a dataFrame object by the pandas dataFrame documentation.

**Comment by nickynicolson** [comment]
Addressed with PR #165  but didn't change terminology re `columns` - it is referred to as a parameter in the pandas documentation in the context of DataFrame creation, rather than how it is used in the lesson.

**Comment by willingc** [comment]
@wrightaprilm I believe @nickynicolson resolved this PR #165 including columns in the context of how it used. Recommend closing this issue.

**Comment by wrightaprilm** [comment]
Good catch.
