### ISSUE TITLE
02 copy example

### ISSUE THREAD

**Issue by tmorrell** [datacarpentry/python-ecology-lesson#160]
Adjust text to suggest that the first copy attempt won't work

We can also reassign values within subsets of our DataFrame. But before we do that, let’s _try to _ make a copy of our DataFrame so as not to modify our original imported data.

```
#try to copy the surveys dataframe so we don't modify the original DataFrame
surveys_copy = surveys_df
```

```
#set the first three rows of data in the DataFrame to 0
surveys_copy[0:3] = 0
```

_At the end of the next section, repeat example code that shows a successful copy_

```
#set the first three rows of data in the DataFrame to 0
surveys_copy[0:3] = 0
surveys_copy.head()
surveys_df.head()
```

**Comment by willingc** [comment]
I'm working on this issue.
