### ISSUE TITLE
02 challenge questions

### ISSUE THREAD

**Issue by tmorrell** [datacarpentry/python-ecology-lesson#161]
These challenge questions

Challenge Activities
What happens when you type:
surveys_df[0:3]
surveys_df[:5]
surveys_df[-1:]
What happens when you call:
dat.iloc[0:4, 1:4]
dat.loc[0:4, 1:4]
How are the two commands different?

Are the exact same as the examples provided in the lesson

**Comment by willingc** [comment]
I'm working on this issue along with #160
