### ISSUE TITLE
code blocks in _extras/guide.md

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/python-ecology-lesson#168]
I moved the INSTRUCTORS.md file to _extras/guide.md, but it seems like code blocks may not be rendering correctly.

Need to fix code blocks in _extras/guide.md

**Comment by willingc** [comment]
This looks pretty good to me. Do you want to check again and let me know where the code isn't rendering correctly or close? @tracykteal

**Comment by wrightaprilm** [comment]
It also looks fine to me.

**Comment by willingc** [comment]
@wrightaprilm Why don't you close and we can always reopen if something comes up later.

**Comment by wrightaprilm** [comment]
Sounds fair to me.
