### ISSUE TITLE
Challenge Statistics nunique() error

### ISSUE THREAD

**Issue by nerdcommander** [datacarpentry/python-ecology-lesson#190]
in the "Challenge - Statistics" section, item #2 asks "What is the difference between len(plot_names) and plot_names.nunique()?"  

I'm assuming that the point is to demonstrate that there is often more than one way to accomplish this (and most tasks) in Python and programming.

the potential problem here is that  the variable `plot_names` contains an array, and the `nunique()` method does not work on an array, only on a pandas series, so you don't get the number of unique items, you get an error.

`plot_names.nunique()` throws an error - `AttributeError: 'numpy.ndarray' object has no attribute 'nunique'`
`surveys_df.plot_id.nunique()` works since the first part produces a series which then works for `nunique()`.

unless the point is to get this error, then my apologies.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by andreas-h** [comment]
can this be closed? seems to be fixed by #198

**Comment by wrightaprilm** [comment]
You are correct, @andreas-h. I entirely forgot this was still open. Thanks all!
