### ISSUE TITLE
/data folder, speciesSubset.csv, and portal_mammals.sqlite

### ISSUE THREAD

**Issue by mikeschwendy** [datacarpentry/python-ecology-lesson#196]
Several of the lessons allude to a /data subfolder containing the surveys.csv and species.csv, but this is not part of the setup.  Moreover, the Combining DataFrames lesson assumes a file named speciesSubset.csv and the sqlite lesson assumes a file called portal_mammals.sqlite, which I could not find reference to in the setup.  

By the Data workflows lesson, it appears that the data folder should have the following contents:
>>> os.listdir('data')
['plots.csv',
 'portal_mammals.sqlite',
 'species.csv',
 'survey2001.csv',
 'survey2002.csv',
 'surveys.csv',
 'surveys2002_temp.csv',
 'yearly_files']

I'm new to this so maybe I'm missing something, but just thought this might be confusing for students.

**Comment by wrightaprilm** [comment]
I went ahead and added these to the setup, thanks for spotting this!
