### ISSUE TITLE
tool for creating parson's problems

### ISSUE THREAD

**Issue by raynamharris** [datacarpentry/python-ecology-lesson#197]
On of our instructor's in training, @pllim, developed a really cool python script for creating parson's problems. You input a few lines of python code, and the output is a scrambled block of code with the indentation removed. This could be a really nice thing to use for creating challenges!

https://github.com/pllim/playpen/blob/master/scramble_codes.py

(Cross posted at swcarpentry/python-novice-inflammation#388 and https://github.com/swcarpentry/python-novice-gapminder/issues/213)

**Comment by pllim** [comment]
Thanks, Rayna! Also see ErinBecker/instructor-training-reorg#33
