### ISSUE TITLE
Character data type in Episode 03

### ISSUE THREAD

**Issue by yeemey** [datacarpentry/python-ecology-lesson#200]
In the episode on data types and format, the data type for strings is referred to as "character." It would be more consistent with the [Python docs](https://docs.python.org/3/library/stdtypes.html#text-sequence-type-str) to rename this as text or text sequence data type. It will also be less confusing, given the introductory sentence of the "Character data type" section: 

> Strings, known as Objects in Pandas, are values that contain numbers and / or characters.

**Comment by wrightaprilm** [comment]
Sure thing. Is this for instructor training checkout (i.e., are you going to submit a pull request making this change, or would you like me to handle it)?

**Comment by yeemey** [comment]
I will make this change, and submit a pull request, thanks!

**Comment by yeemey** [comment]
Yes, this is for instructor training checkout.

**Comment by wrightaprilm** [comment]
Addressed by #201. Thank you!
