### ISSUE TITLE
additional "required" data needed in setup

### ISSUE THREAD

**Issue by ellamguest** [datacarpentry/python-ecology-lesson#220]
The [setup](http://www.datacarpentry.org/python-ecology-lesson/setup) only lists 4 data files to download individually:
- surveys.csv, species.csv, speciesSubset.csv, and portal_mammals.sqlite

The lesson ['04-merging-data'](http://www.datacarpentry.org/python-ecology-lesson/04-merging-data/) references ['the data folder'](https://github.com/datacarpentry/python-ecology-lesson/tree/gh-pages/data) which contains additional required files:
- survey2001.csv, survey2002.csv, and plot.csv

These files need to be added to the data setup section - either individually or as a whole folder.

**Comment by wrightaprilm** [comment]
Fixed in  48f560e. Thanks!
