### ISSUE TITLE
Bug BBQ: Data setup confusion

### ISSUE THREAD

**Issue by colinmorris** [datacarpentry/python-ecology-lesson#221]
The "Data" section of the [setup document](http://www.datacarpentry.org/python-ecology-lesson/setup/) says:

> For this lesson, we will use two files for the data. Download these files to your computer. Once you click on them they will be automatically downloaded to your default download directory.

I see a few problems here.

1. There are actually 7 files listed after this, not 2.
2. It is not true that clicking each link will initiate a download. This happens with the figshare links, but the links to the github-hosted files bring up a web preview. (To download the file, you need to click the "raw" button, then "save page as").
3. There doesn't seem to be any guidance about about making these files findable in the Python environment that the students set up.

1 and 2 are pretty minor problems, but I think 3 is something that students could easily get stuck on.

If I just follow the setup instructions, the first time I call `pd.read_csv("surveys.csv")` in the [Starting With Data](http://www.datacarpentry.org/python-ecology-lesson/01-starting-with-data/) lesson, I'm going to get an error, because Python is running from my home directory (or whatever the pwd happened to be when I ran `jupyter notebook`) and the csv files are in my Downloads directory.

Also, it's worth pointing out that some lessons even make different assumptions about the relative path to the data. e.g. the [Data Types and Formats](http://www.datacarpentry.org/python-ecology-lesson/03-data-types-and-format/) lesson has the line `surveys_df = pd.read_csv("data/surveys.csv")`.

## Suggested solution

I'd suggest adding a section to the setup document (before the "Data" section) about setting up a working directory. There's a good example of this in the [R ecology lesson](http://www.datacarpentry.org/R-ecology-lesson/00-before-we-start.html#organizing_your_working_directory).

Lessons/setup should be amended to clarify that...
- when starting the interpreter or the notebook server, students should be in the working directory they created during setup.
- data files should be saved to the `data/` subdirectory of their working directory

And paths to data files in the code examples should be made to consistently use the `data/` prefix.

Another minor suggestion: It would be a nice little time-saving measure to host a zip file containing all 7 data files, just to save some clicking.

**Comment by cmaimone** [comment]
One way to provide the ability to download the files as single zip file, while not creating issues with keeping the zip file updated as the data files change, is to use [DownGit](https://minhaskamal.github.io/DownGit/#/home).  

This link: https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/datacarpentry/python-ecology-lesson/tree/gh-pages/data can be used to download everything in the data folder as a single zip file.

I'd do a PR to add this to the Setup page, but I'm not sure if the files in the yearly_files subdirectory of the data directory should be downloaded by everyone.  There is also a bouldercreek file in the data directory that is not currently referenced on the setup page.

**Comment by wrightaprilm** [comment]
Would it be possible to do two zip files, one without the yearly files and one with? I put them there in case there were learners who encountered permissions issues creating directories from the command line and couldn't complete the exercise in which they're created. So it would be nice to have them in a zip, but I also don't think it's necessary. 

I'll add the bouldercreek file to the setup. It's referenced in lesson 7, but is very seldom taught because you really need a second session to get all the way through it, and most workshops choose to allocate that time in some other way.

**Comment by cmaimone** [comment]
No, you can only do an entire directory with the various services like this that I've used.  If the supplemental files were moved out of data to another directory, that could work.  Or, it might not be that bad to have them included.  The extra files aren't particularly large, so it's not much of a burden if people have downloaded files they don't end up needing.

**Comment by wrightaprilm** [comment]
In that case, I think it's fine to include them. They're not big.

**Comment by wrightaprilm** [comment]
Download issue addressed by #231. Checking of paths still open, and would make a great instructor checkout activity!

**Comment by joshsteele** [comment]
Hi.  I'd be happy to go through and check the paths to the data throughout the lesson. I'm working on my instructor checkout.

**Comment by wrightaprilm** [comment]
Awesome, @joshsteele. Let me know if you need any help with anything.

**Comment by joshsteele** [comment]
Thanks, I will let you know.

**Comment by wrightaprilm** [comment]
Path issues addressed by PR #233. I'm going to leave this open, since the issue of instructing learners on where to put the data is unaddressed and would be a nice checkout project for someone.
Thanks everyone for your work so far!

**Comment by wrightaprilm** [comment]
The discussion on this sort of petered out, I'm going to add one action item:

- [ ] Add discussion of where to store downloaded data files to instructor guide. Where should instructors tell them to save it? What files should be present? How can downloading files and storing them be used to enforce Data Carpentry's other materials about good project organization?

**Comment by wrightaprilm** [comment]
Superseded by #306.
