### ISSUE TITLE
'If loop' is potentially confusing terminology

### ISSUE THREAD

**Issue by colinmorris** [datacarpentry/python-ecology-lesson#225]
It's used throughout [lesson 05](http://www.datacarpentry.org/python-ecology-lesson/05-loops-and-functions/). 

I think the word "loop" might give the impression that these things go around and round like for loops, executing more than once.

I'd suggest renaming to "if statement" (or "conditional", or "if/else").

**Comment by tdpearson** [comment]
I agree and have created the above PR.

**Comment by wrightaprilm** [comment]
Solved by #227.
