### ISSUE TITLE
consistent usage of the `data` folder

### ISSUE THREAD

**Issue by stijnvanhoey** [datacarpentry/python-ecology-lesson#229]
In the `setup` and first lessons, the usage of a `data` folder is not mentioned or used. However, when starting with the lesson of dat types and formats, the read data is reading from a data folder:
```
surveys_df = pd.read_csv("data/surveys.csv")
```
I think consistency matters here and I would propose to use the `data` folder for all episodes (splitting notebooks and data files in separate folders), but before I put this into a PR, I just want to check if I'm not missing something?

**Comment by wrightaprilm** [comment]
You’re right, and this is what we reference as an issue in #221. A PR on data/ consistency would be great. Just for simplicity, I’m going to close this one and have you reference issue #221 in your PR. Thanks!
