### ISSUE TITLE
Update objectives in 'Short Introduction to Programming in Python'

### ISSUE THREAD

**Issue by mialondon** [datacarpentry/python-ecology-lesson#230]
The objectives currently live at http://www.datacarpentry.org/python-ecology-lesson/00-short-introduction-to-Python/ are:
- Describe the advantages of using programming vs. completing repetitive tasks by hand.
- Define the following data types in Python: strings, integers, and floats.
- Perform mathematical operations in Python using basic operators.
- Define the following as it relates to Python: lists, tuples, and dictionaries.

Based on the 'evaluating objectives' exercise in training today, the following changes might be helpful:
- The objectives description could be more learner-centred. ‘By the end of this lesson you will be able to:’
- ‘Define the following data types in Python: strings, integers, and floats’ -> ‘Define and discuss when to use…’ Similarly for tuples etc 
- It doesn’t explain the advantages of scripted vs manual tasks (unless it’s in the instructor material and not on the lesson page)
- It also very briefly mentions how to create functions (but not what they are) - the objectives could include 'introducing functions in Python', but ideally a few lines of explanation could be added to that section first.

**Comment by wrightaprilm** [comment]
OK, would you like to submit a pull request with these changes, or would you like me to tag these as available for contributors to try?
