### ISSUE TITLE
Typos in Lesson 03 - Data Types and Formats

### ISSUE THREAD

**Issue by jberlanga** [datacarpentry/python-ecology-lesson#241]
Under Numeric Data Types:  Missing comma after

> For example: 1.13, 2.0

---

Under Text Data Type: Missing space after 

> If a column contains numbers and NaNs
 
---

Under Where Are the NaN's?: Missing punctuation 

> (ie select meaningful weight values)

---

Under Writing Out Data to CSV: 

- `dropna` misspelled as `drop_na` in two places
- Following line should have `drop_na` replaced by `df_na`:

> If you now type `drop_na`, you should observe that the resulting DataFrame has...

- Following line should be reworded slightly to improve understanding:

> We can save it to a different folder by adding the foldername and a slash to the file `df1.to_csv('foldername/out.csv').

- Reference to `vertical_stack` should be changed to `df_na`

**Comment by wrightaprilm** [comment]
It looks like you cleaned all these up in #242. Thank you! I'll got ahead and close this.
