### ISSUE TITLE
"Intro to Python" no longer showing up in overall schedule

### ISSUE THREAD

**Issue by MikeTrizna** [datacarpentry/python-ecology-lesson#243]
We are about to teach a Data Carpentry course today, and just noticed that the "Short Introduction to Programming in Python" episode is no longer listed on the main Python for Ecologists index (http://www.datacarpentry.org/python-ecology-lesson/).

I unfortunately don't know how to work with Jekyll, but it appears that the portion that automatically generates the Schedule portion of the page is located in [_includes/syllabus.html](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/_includes/syllabus.html). Something about either the code there, or in the [Intro to Python episode markdown](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/_episodes/00-short-introduction-to-Python.md) is causing this lesson to be skipped.

I noticed that the Intro to Python lesson was mentioned recently in Issue #230 so that could possibly be the root of the problem.

**Comment by wrightaprilm** [comment]
Thanks much for catching that. The issue was that the "keypoints" section in the header isn't supported by the current template, and so jekyll was not understanding that lesson as a lesson. Went in and pulled that out and we're good to go!

**Comment by MikeTrizna** [comment]
Wow, that was fast! (So fast that I went to show the bug to my co-instructor, it was already fixed, and I was questioning my sanity). Thanks for fixing this @wrightaprilm.

**Comment by wrightaprilm** [comment]
Ha, I try to get to emergency issues like this ASAP.

Let me know how the lesson runs - we're planning another Issue Bonanza and Bug BBQ, so we'll have some devoted time to patch a lot of the little things that slip by throughout the year.
