### ISSUE TITLE
Bug BBQ: 07-Putting it all together lesson cleanup

### ISSUE THREAD

**Issue by wrightaprilm** [datacarpentry/python-ecology-lesson#254]
This lesson has been needing a bit of attention for a while. I wanted to solicit a little bit of feedback before I make a to-do list for the Bug BBQ. 

- [ ] #245 suggests adding the idea of column splitting. The Open refine lessons accomplish this using [this file](https://ndownloader.figshare.com/files/7823341). It's huge, but it's basically the Portal Mammal dataset, and the splitting is of the scientificName column into Genus and Species columns. 
This can also be a springboard to discuss the skip_rows argument to the read_csv function. I've committed a copy of the csv file to our data repo, if people would like to look at it.

- [ ] I think we should use the code
```
df[["genus", "species"]] = df["scientificName"].str.split(" ", expand=True)

```
to perform the split. We can also discuss what str.split does in this particular context.

- [ ] Combine the three column date system into a pandas dt object.

- [ ] The plots in the lesson are quite old, from the old Matplot lessons. Per #246, we are switching over to plotnine, so we should rework the plots into that library. We get a variety of suggestions about plotting, and I think we can be flexible to types of plots that might be useful to our learners. Plotting is sort of my weak spot, so I'm leaning heavily on the community here.

Thoughts?

**Comment by katrintirok** [comment]
I am a bit unsure what the main aim of this lesson is - it sounds like it should be kind of a capstone project, which is a good idea I think, but doesn't really come together like this at the moment.

What would be necessary to make it a capstone project?, some ideas:
1) decide on data to use --> learners could use their own data or use a given data set (seems to be fine as is)
2) explore data a bit outside of python
3) clean data if necessary - either using OpenRefine or python
4) find a scientific question to ask about the data
5) do the necessary steps - e.g. summarising, averaging ...
6) do a visualisation using preferred plotting library (?)
7) export cleaned/summarised data and nice graph
