### ISSUE TITLE
No Python syntax highlighting

### ISSUE THREAD

**Issue by colinmorris** [datacarpentry/python-ecology-lesson#266]
There seems to be no syntax highlighting of the python code in this lesson - it all just appears grey. 

(Compare with the [programming with Python](http://swcarpentry.github.io/python-novice-inflammation) SWC lesson, or the DC [R ecology lesson](http://www.datacarpentry.org/R-ecology-lesson/), both of which have syntax highlighting.)

**Comment by tmorrell** [comment]
I've updated the formatting in a few places in https://tmorrell.github.io/python-ecology-lesson/06-visualization-ggplot-python/, but it didn't seem to fix the syntax highlighting.  Might be configuration of the template?

**Comment by fmichonneau** [comment]
Yes, the template hasn't been updated in a while. If you submit a PR fixing the style formatting, I'll take care of bringing the latest version of the template.

**Comment by wrightaprilm** [comment]
I'm a little confused about the new template and the role of the new template in formatting - should we have gotten a pull request from Raniere with the template? And if not, should we wait until it is received to make these format changes?

**Comment by trallard** [comment]
The latest update for the template should fix the lack of syntax highlighting.  
I think what @fmichonneau meant is that he'll take care of bringing the new template to the lesson instead of waiting for a PR from Raniere

**Comment by fmichonneau** [comment]
@trallard is correct. The Data Carpentry lessons that use the SWC template are not part of the script that Raniere uses to conduct the upgrade yet, which is why you haven't received a PR from him. All the DC lessons that use the template will be added to the script before the next  template release.

**Comment by tmorrell** [comment]
PR submitted. The formatting won't change until the template is updated.
