### ISSUE TITLE
Solution code in episode 06 (ggplot) not rendered as code

### ISSUE THREAD

**Issue by colinmorris** [datacarpentry/python-ecology-lesson#267]
In [this lesson](http://www.datacarpentry.org/python-ecology-lesson/06-visualization-ggplot-python/) the solution code isn't styled as a code block (i.e. not monospace, no grey background).

**Comment by tmorrell** [comment]
Should be fixed in #271

**Comment by wrightaprilm** [comment]
The issue is persisting, but I'm going to close this issue, and have us manage the discussion via issue #266.
