### ISSUE TITLE
No output (tables or charts) shown in episode 06 (plotting)

### ISSUE THREAD

**Issue by colinmorris** [datacarpentry/python-ecology-lesson#268]
It would be really useful to see the plots produced by the code in the episode, as well as excerpts of the dataframes used.

(Maybe this work is already planned, but I couldn't find any issues/PRs about it.)

**Comment by tmorrell** [comment]
Available in #271. Rendered version available at https://tmorrell.github.io/python-ecology-lesson/06-visualization-ggplot-python/

**Comment by wrightaprilm** [comment]
It is indeed - thanks to both of you for raising the issue!
