### ISSUE TITLE
Episode06 faceting challenge questions

### ISSUE THREAD

**Issue by tmorrell** [datacarpentry/python-ecology-lesson#270]
The solutions for the faceting challenge questions have issues.  The first generates a warning:

/Users/tmorrell/anaconda/lib/python3.6/site-packages/plotnine/geoms/geom_path.py:82: UserWarning: geom_path: Each group consist of only one observation. Do you need to adjust the group aesthetic?
  warn("geom_path: Each group consist of only one "

![faceting](https://user-images.githubusercontent.com/10798874/39211663-317fa642-47c1-11e8-8ee9-f3a81aa9069d.png)

Perhaps some sort of interpolation is needed?

The second challenge question solution does not work at all and returns the error:

PlotnineError: 'At least one layer must contain all variables used for facetting'

**Comment by drlabratory** [comment]
Having just run into this in the R version, this warning happens when you run the code on data that hasn't been filtered. The fact that PX and RX (and others) are in the example plot suggests that`surveys_complete = surveys_complete.dropna()` was not run before running the answer code.

**Comment by wrightaprilm** [comment]
Thanks for finding the issue here, @drlabratory. Since we've restructured the lessons and this code no longer appears anywhere, I'm going to call this one "Mystery Solved 👻" and close it up!

**Comment by maxim-belkin** [comment]
Shall we add info about this to instructor notes?

**Comment by wrightaprilm** [comment]
I have mixed feelings - in the new lesson, not dropping NA will be an issue. For the first several plots, p9 drops them for you. For the facets, it returns an error. But the drop statement is in the same cell as the read in statement. So my inclination is either "no", or that such info should go directly into the lesson.
