### ISSUE TITLE
Plotnine not listed in setup & ggplot package not found in conda

### ISSUE THREAD

**Issue by riwoodward** [datacarpentry/python-ecology-lesson#272]
Hi,

I tried following this lesson (as part of the new instructor checkout process) and there seems to be a problem with the setup and use of ggplot package.

**Problem 1: ggplot package is not found**
In the setup page, it instructs learners to install ggplot using the following command:

    conda install -c bokeh ggplot

On my machine (Anaconda distribution, Win10), I get the following error message:

    Solving environment: failed

    PackagesNotFoundError: The following packages are not available from current channels:

      - ggplot

    Current channels:

      - https://conda.anaconda.org/bokeh/win-64
      - https://conda.anaconda.org/bokeh/noarch
      - https://conda.anaconda.org/anaconda-fusion/win-64
      - https://conda.anaconda.org/anaconda-fusion/noarch
      - https://repo.anaconda.com/pkgs/main/win-64
      - https://repo.anaconda.com/pkgs/main/noarch
      - https://repo.anaconda.com/pkgs/free/win-64
      - https://repo.anaconda.com/pkgs/free/noarch
      - https://repo.anaconda.com/pkgs/r/win-64
      - https://repo.anaconda.com/pkgs/r/noarch
      - https://repo.anaconda.com/pkgs/pro/win-64
      - https://repo.anaconda.com/pkgs/pro/noarch
      - https://repo.anaconda.com/pkgs/msys2/win-64
      - https://repo.anaconda.com/pkgs/msys2/noarch

    To search for alternate channels that may provide the conda package you're
    looking for, navigate to

        https://anaconda.org

    and use the search bar at the top of the page.

**Problem 2: plotnine is not installed**
In the plotting page, it seems the plotnine package is used. However, the learners don't appear to be instructed to install this.

Perhaps some information from the plotnine page should be included:
http://plotnine.readthedocs.io/en/stable/installation.html

Finally, as a personal comment, I find the plotting part of this lesson unnecessarily confusing. Matplotlib is the standard plotting tool which is widely used (with excellent online information and a long-term maintenance commitment), whereas plotnine / ggplot on Python appears somewhat experimental (plotnine isn't on the main conda channel and requires a customised install command to use conda forge - when I tried running this, it wanted to downgrade some of my packages which is annoying). I appreciate this is part of a wider discussion however, e.g. in Issue #246

**Comment by wrightaprilm** [comment]
Addressed via #269. Thanks!
