### ISSUE TITLE
Objective not addressed?

### ISSUE THREAD

**Issue by erikamias** [datacarpentry/python-ecology-lesson#289]
Objective "Describe the advantages of using programming vs. completing repetitive tasks by hand." is not described in the lesson?

**Comment by maxim-belkin** [comment]
Quick `grep` returned: [01-short-introduction-to-Python.md](https://github.com/datacarpentry/python-ecology-lesson/blame/gh-pages/_episodes/01-short-introduction-to-Python.md#L9)
