### ISSUE TITLE
"Batteries included" is a lie for data science

### ISSUE THREAD

**Issue by amueller** [datacarpentry/python-ecology-lesson#30]
The intro says

> "Batteries Included" philosophy - libraries for common tasks available in standard installation

I would argue that the opposite is true. Coming from R or Matlab, people are very surprised that you need to install / import a library (numpy) to get matrices. And a different one for dataframes.
Installing numpy also is a major pain on most operating systems, unless you use anaconda.
Does "standard installation" mean anaconda? Then the instruction should say that.

A novice might thing "standard installation" means the one from python.org. Imagine someone on windows installing the python.org interpreter and expecting batteries included.

[for context: I'm a strong advocate for the use of Python in data science.]

**Comment by mkuzak** [comment]
I agree it does hold for Anaconda distribution, which is default for DC but not necessarily standard for Python.
I'm curious what others think, I'm not against removing it. I think "general purpose" or "all around" may better describe Python as a programming language.

**Comment by ctb** [comment]
+0 for "general purpose" over "batteries included."

**Comment by qjcg** [comment]
I'd go with "general purpose" as well.

**Comment by hugobowne** [comment]
"general purpose" is great. I am also fine with "batteries included", if the full anaconda distribution is referenced explicitly, which currently is great practice for beginners :)
