### ISSUE TITLE
Little improvements, typos, comments etc to episodes

### ISSUE THREAD

**Issue by orchid00** [datacarpentry/python-ecology-lesson#326]
Hi maintainers, while translating the lesson, we found some little typos and comments missing. I have suggested to send pull requests to this lesson (as it is the original lesson).

Would you welcome PR with these kind of small fixes? linked with this issue
Or would you like to have one open issue for each PR?

**Comment by maxim-belkin** [comment]
Hey, @orchid00!
No need to create issues - proceeding with pull requests is fine. Personally, I prefer to deal with typos on a pr-per-episode basis.
