### ISSUE TITLE
Using the "attribute" syntax for accessing columns, and issues related to reserve words

### ISSUE THREAD

**Issue by alexetnunes** [datacarpentry/python-ecology-lesson#351]
In the [indexing, slicing, etc. lesson](https://datacarpentry.org/python-ecology-lesson/03-index-slice-subset/index.html) the two methods to access a single column of data are mentioned, using square brackets and accessing it like an attribute.

However, if a column is named the same as method it cannot be accessed as an 'attribute'. The result changes, either returning an error or returning the bound method object. But it's not what is expected.

My suggestion would be to insert a warning/exercise to showcase this possibility. I ran into this a lot when using `groupby()` and `agg()` and naming new columns either `count` or `mean`. Then getting the error or bound method object back. This warning could be in the form of a note or more of an exercise to see what happens when the namespaces are infringed upon.

**Comment by wrightaprilm** [comment]
Ah ... I don't believe we ever discuss reserve words. This might be a good place to do it. I'll change the name of this to indicate that this would be a good checkout-issue.

**Comment by maxim-belkin** [comment]
> New users might not know not to name a list "list" or similar.

This is even a more interesting use-case. Although one can do `list = [1, 2, 3]`, they would then be unable to execute `list(sometuple)` or even `list()` (to create an empty list)...
