### ISSUE TITLE
Ep1: No explanation of 'hashable'

### ISSUE THREAD

**Issue by gcapes** [datacarpentry/python-ecology-lesson#359]
https://datacarpentry.org/python-ecology-lesson/01-short-introduction-to-Python/index.html#dictionaries

> Keys can only have particular types - they have to be “hashable”. Strings and numeric types are acceptable, but lists aren’t.

**Comment by gnguyen27** [comment]
I couldn't find the reference of this issue on the lesson. Is this problem has been fixed and should be closed?

**Comment by maxim-belkin** [comment]
We addressed this in 104cacc. Thanks for the reminder, Gia!
