### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by amueller** [datacarpentry/python-ecology-lesson#36]
I haven't found any installation instructions. Maybe I missed it.

**Comment by hugobowne** [comment]
I'd happily write and include installation instructions. They could go in [intro](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/00-short-introduction-to-Python.md) or have their own .md ? 

[Here](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/index.md) it states that '[Data Carpentry] will provide instructions on setting up the required software several days in advance' so the instructions exist, I just need to get my hands on them to do this.

thoughts, @wrightaprilm ?

**Comment by tracykteal** [comment]
@amueller @hugobowne thanks for bringing this up. I see, the template that included installation instructions didn't make it over to the Python lesson. I've updated index.md and the file _includes/pythonSetup.html that includes the installation instructions in https://github.com/datacarpentry/python-ecology-lesson/pull/75

Can you check to make sure that things look and work OK? Thanks!
