### ISSUE TITLE
Ep1: Better choice of dictionary keys

### ISSUE THREAD

**Issue by gcapes** [datacarpentry/python-ecology-lesson#360]
https://datacarpentry.org/python-ecology-lesson/01-short-introduction-to-Python/index.html#dictionaries

When introducing a dictionary, numeric keys are used. This confuses things slightly because it makes it seem that dictionaries can be indexed in the same way as lists, using numbers. I think it would be clearer to use something text-based for the first example.

**Comment by maxim-belkin** [comment]
Thanks, Gerard! Very good issue that makes an important point.
Glad we fixed it before its first birthday :)
