### ISSUE TITLE
Move solutions to exercises back to episodes

### ISSUE THREAD

**Issue by gcapes** [datacarpentry/python-ecology-lesson#361]
At least in the early episodes, most exercises don't have solutions.

**Comment by maxim-belkin** [comment]
Solution are in the instructor notes... we need to move them

**Comment by wrightaprilm** [comment]
As they are in the SWC-python? I'm fine with that. The thing to do about this might be to branch, and add all the solutions, then merge so there's a uniform roll-out.

**Comment by maxim-belkin** [comment]
I meant here: https://datacarpentry.org/python-ecology-lesson/guide/

**Comment by wrightaprilm** [comment]
Right, but you're proposing to move the answers out of there and into the lesson in a code fold?

**Comment by maxim-belkin** [comment]
Oh, my apologies -- misread part of your previous response. Yes, this is exactly what I'm proposing (with appropriate modifications, of course).

**Comment by wrightaprilm** [comment]
@maxim-belkin and I had a brief discussion on this, and we'd like to proceed like so:

1. We will adopt the swc-py style solutions format. See [here](https://github.com/swcarpentry/python-novice-inflammation/blob/gh-pages/_episodes/01-numpy.md) for an example, about 60% of the way down the page.

2. We would like one PR per lesson adopting this style. Each will be tested by us and merged once each lesson has one. 

3. We'd like this done by the summer lesson release (late June).

This is a beginner-friendly activity and would be great for someone who is interested in learning a little more about how the lesson template works. If no one wants to try, Max and I will handle it prior to the release.

**Comment by btovar** [comment]
Fixed in #542
