### ISSUE TITLE
Bad links in Data Analysis and Visualization in Python for Ecologists: Setup

### ISSUE THREAD

**Issue by ebeagle1** [datacarpentry/python-ecology-lesson#368]
In the Data Analysis and Visualization in Python for Ecologists: Setup lesson page (https://datacarpentry.org/python-ecology-lesson/setup) the links for download of Anaconda and Miniconda direct to pages that no longer exist. 

The following links appear to be the most up to date for download of these programs.
Anaconda: https://www.anaconda.com/distribution/
Miniconda: https://docs.conda.io/en/latest/miniconda.html

**Comment by maxim-belkin** [comment]
Thanks, @ebeagle1.
Would you like to submit a PR fixing these links? I'd be happy to help you with that.

**Comment by ebeagle1** [comment]
Yes – that would be great!

**Comment by maxim-belkin** [comment]
Great! So, here are the steps:

1. Navigate to https://github.com/datacarpentry/python-ecology-lesson and fork this repository:

    ![Screen Shot 2019-04-05 at 13 38 57](https://user-images.githubusercontent.com/13123663/55649322-3aa2b080-57d2-11e9-9838-74b838d53a60.png)

<br>
<br>

2. Navigate to your fork (it will be located at https://github.com/ebeagle1/python-ecology-lesson)
and create a new branch:

    ![Screen Shot 2019-04-05 at 13 41 08](https://user-images.githubusercontent.com/13123663/55649605-e9df8780-57d2-11e9-819f-ae72cc26fc2d.png)

    You should see a "Branch created" message and GitHub will switch you to that new branch:

    ![Screen Shot 2019-04-05 at 13 47 18](https://user-images.githubusercontent.com/13123663/55649778-6f633780-57d3-11e9-99bc-202308cec99c.png)

3. Now you have to change the file that is rendered as https://datacarpentry.org/python-ecology-lesson/setup. As you could guess, this file is called `setup.md`. It is at the very bottom of the list of files in the root folder.

    ![Screen Shot 2019-04-05 at 13 51 18](https://user-images.githubusercontent.com/13123663/55649962-eb5d7f80-57d3-11e9-9745-eb6a336493c3.png)

   Click on its name (`setup.md`). You should see this:

    ![Screen Shot 2019-04-05 at 13 53 04](https://user-images.githubusercontent.com/13123663/55650095-42fbeb00-57d4-11e9-9646-93d492609838.png)
 
    Click on the pencil (or pen?) icon. You will find yourself in a text editor -- make appropriate changes. Scroll to the bottom of the page, specify a good title for your changes, provide any additional details, and click "Commit changes":

    ![Screen Shot 2019-04-05 at 13 57 56](https://user-images.githubusercontent.com/13123663/55650395-1e544300-57d5-11e9-8317-20736d3fc18f.png)

4. Navigate back to this repository at https://github.com/datacarpentry/python-ecology-lesson. You should see a yellow strip with a green "Compare and pull request" button:

    ![Screen Shot 2019-04-05 at 14 01 59](https://user-images.githubusercontent.com/13123663/55650494-67a49280-57d5-11e9-9256-3a8428f41fca.png)

5. On a new page, add any additional information about your changes, remove the PR template text and click "Create pull request":

    ![Screen Shot 2019-04-05 at 14 03 44](https://user-images.githubusercontent.com/13123663/55650656-e39eda80-57d5-11e9-970b-82011f45b338.png)

**Comment by Lazigerbill** [comment]
Fixed submitted, please accept PR =)

**Comment by maxim-belkin** [comment]
> Fixed submitted, please accept PR =)

Are you @ebeagle1 ?

**Comment by Lazigerbill** [comment]
> > Fixed submitted, please accept PR =)
> 
> Are you @ebeagle1 ?

No I am not, currently taking the trainer training course and was looking for ways to contribute as an exercise. ;P
Nice to meet you.

**Comment by quist00** [comment]
Closing issue for following reasons:

- Original Setup page moved. 
- New setup encourages full anaconda with working url / guidance for three major platforms and contains no links to miniconda that I could find.  
- Package information for miniconda users left in as a self-service convenience for presumed more experienced users.
