### ISSUE TITLE
matplotlib explains mostly config options, not different kinds of plots

### ISSUE THREAD

**Issue by amueller** [datacarpentry/python-ecology-lesson#37]
I feel that different kinds of plots is something is important to know, like scatter plots, box plots, heatmaps etc...
The options that are explained also don't seem that important to beginners, like dpi, which seems a pretty advanced concept.

**Comment by willingc** [comment]
@tracykteal I recommend closing this issue too. Lesson 7 adds a number of plots and the challenge exercise at the end links to the excellent (recently update) [matplotlib docs on plot types](http://matplotlib.org/users/screenshots.html)

**Comment by wrightaprilm** [comment]
I agree, and had meant to close this when we merged the new lesson 7.
