### ISSUE TITLE
possibly broken URLs

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/python-ecology-lesson#389]
In preparation for the June 2019 release, we are looking for broken links in the lessons. We identified the links below as possibly being problematic:

```
 ● Resource: `setup`
    Message: ‘File referenced by URL doesn't exist.’
    Found in:
    - /home/francois/git/ecology-lessons/python-ecology/_site/index.html
 ● Resource: `http://ggplot2.org/`
    Message: ‘HTTP status code: 404’
    Found in:
    - /home/francois/git/ecology-lessons/python-ecology/_site/07-visualization-ggplot-python/index.html
  ● Resource: `https://spyder-ide.github.io`
    Message: ‘HTTP status code: 404’
    Found in:
    - /home/francois/git/ecology-lessons/python-ecology/_site/00-before-we-start/index.html
  ● Resource: `http://pandas.pydata.org/pandas-docs/stable/visualization.html#basic-plotting-plot`
    Message: ‘URL is valid but fragment (hash reference): 'basic-plotting-plot' not found in page.’
    Found in:
    - /home/francois/git/ecology-lessons/python-ecology/_site/02-starting-with-data/index.html
  ● Resource: `https://plotnine.readthedocs.io/en/stable/api.html#Color-and-fill-scales`
    Message: ‘URL is valid but fragment (hash reference): 'Color-and-fill-scales' not found in page.’
    Found in:
    - /home/francois/git/ecology-lessons/python-ecology/_site/07-visualization-ggplot-python/index.html
  ● Resource: `http://pandas.pydata.org/pandas-docs/stable/dsintro.html#dataframe`
    Message: ‘URL is valid but fragment (hash reference): 'dataframe' not found in page.’
    Found in:
    - /home/francois/git/ecology-lessons/python-ecology/_site/02-starting-with-data/index.html
  ● Resource: `https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#incident-reporting-guidelines`
    Message: ‘URL is valid but fragment (hash reference): 'incident-reporting-guidelines' not found in page.’
    Found in:
    - /home/francois/git/ecology-lessons/python-ecology/_site/CODE_OF_CONDUCT.html
```

Let me know if you have any questions. Thanks!

**Comment by wrightaprilm** [comment]
Hi @fmichonneau. Thanks for this. We had also previously discussed moving entirely to not hosting data in the repository. The last remaining files to move to FigShare were speciessubset, a file generated by us from the total data set, and Boulder Creek.  Discussion on this is in #306. Do you have the information you need on these to add them to FigShare?

Just putting the rest into a checklist for my own reference.

- [ ] Resource: `setup`
    Message: ‘File referenced by URL doesn't exist.’
    Found in:
    - /home/francois/git/ecology-lessons/python-ecology/_site/index.html
- [x]  Resource: `http://ggplot2.org/`
    Message: ‘HTTP status code: 404’
    Found in:
    - /home/francois/git/ecology-lessons/python-ecology/_site/07-visualization-ggplot-python/index.html
- [x] Resource: `https://spyder-ide.github.io`
    Message: ‘HTTP status code: 404’
    Found in:
    - /home/francois/git/ecology-lessons/python-ecology/_site/00-before-we-start/index.html
- [ ] Resource: `http://pandas.pydata.org/pandas-docs/stable/visualization.html#basic-plotting-plot`
    Message: ‘URL is valid but fragment (hash reference): 'basic-plotting-plot' not found in page.’
    Found in:
    - /home/francois/git/ecology-lessons/python-ecology/_site/02-starting-with-data/index.html
- [x] Resource: `https://plotnine.readthedocs.io/en/stable/api.html#Color-and-fill-scales`
    Message: ‘URL is valid but fragment (hash reference): 'Color-and-fill-scales' not found in page.’
    Found in:
    - /home/francois/git/ecology-lessons/python-ecology/_site/07-visualization-ggplot-python/index.html
- [ ] Resource: `http://pandas.pydata.org/pandas-docs/stable/dsintro.html#dataframe`
    Message: ‘URL is valid but fragment (hash reference): 'dataframe' not found in page.’
    Found in:
    - /home/francois/git/ecology-lessons/python-ecology/_site/02-starting-with-data/index.html
- [ ] Resource: `https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#incident-reporting-guidelines`
    Message: ‘URL is valid but fragment (hash reference): 'incident-reporting-guidelines' not found in page.’
    Found in:
    - /home/francois/git/ecology-lessons/python-ecology/_site/CODE_OF_CONDUCT.html

**Comment by maxim-belkin** [comment]
`setup` is not broken in the online version, just like `guide`

**Comment by fmichonneau** [comment]
@wrightaprilm I'll try to look again into the data, I think last time I checked was during the government shutdown and the website wasn't fully working.

@maxim-belkin  while online the URL: `https://datacarpentry.org/python-ecology-lesson/setup` works, it won't work for the offline version of the website (which we try to support as much as possible). Using `{% link setup.md %}` in the source should fix it.

For the Coc link, using the most recent version of links from the style should take care of it.

**Comment by maxim-belkin** [comment]
> @maxim-belkin while online the URL: `https://datacarpentry.org/python-ecology-lesson/setup` works, it won't work for the offline version of the website (which we try to support as much as possible).

Yeah, that's what I said.

>  Using `{% link setup.md %}` in the source should fix it.

We already have `lesson-setup` in `links.md`

**Comment by maxim-belkin** [comment]
Almost all links have been fixed.
I wonder why `(guide)` link in `index.md` is not broken locally....

**Comment by maxim-belkin** [comment]
@fmichonneau, could you please re-run your check tool once again?

**Comment by fmichonneau** [comment]
everything looks good on my end. Thanks!

**Comment by maxim-belkin** [comment]
Thanks, François!
