### ISSUE TITLE
Missing data files in setup

### ISSUE THREAD

**Issue by jensentobias** [datacarpentry/python-ecology-lesson#409]
There seems to be missing some data files for episode "[Combining DataFrames with Pandas](https://datacarpentry.org/python-ecology-lesson/05-merging-data/index.html)" as described in the episode "[Setup](https://datacarpentry.org/python-ecology-lesson/setup.html)". In particular

Files `survey2001.csv` and `survey2002.csv`:
Used in episode "Combining DataFrames with Pandas", but not on the mentioned [FigShare](https://figshare.com/articles/Portal_Project_Teaching_Database/1314459), nor the zip [download link](https://github.com/weecology/portal-teachingdb/archive/master.zip), nor the list mentioned on the [setup page](https://datacarpentry.org/python-ecology-lesson/setup.html). The files are located in the [repository](https://datacarpentry.org/python-ecology-lesson/setup.html). The issue might originate from moving around episodes, since the following episode "Data Workflows and Automation", will generate these files. But its problematic with the current order.

File `speciesSubset.csv`:
Used in episode "Combining DataFrames with Pandas", but not on the mentioned [FigShare](https://figshare.com/articles/Portal_Project_Teaching_Database/1314459), nor the zip [download link](https://github.com/weecology/portal-teachingdb/archive/master.zip). Is however on the list mentioned on the [setup page](https://datacarpentry.org/python-ecology-lesson/setup.html).

Am I missing something? As a step one, could one confirm this issue. If one of the maintainers would like a PR for this, please let me know.

**Comment by wrightaprilm** [comment]
Yes, we've been in the process of trying to sync the data files to the Figshare for a bit. We've included the files `surveys2001.csv` and `surveys2002.csv` in the repository so the instructor can provide them if any participants have issues. But since they're expected to be generated, we've historically left them out. 

The `speciesSubset.csv`, on the other hand isn't part of the "canonical" Portal Project files. So that is sort of an issue, since Data Carpentry doesn't own those resources. 

I think the way forward is to remove the link to the zip download file link, since we don't have control over it. What do you think, @maxim-belkin?

**Comment by maxim-belkin** [comment]
Figshare and zip archive are related (through https://github.com/weecology/portal-teachingdb): 

_from the Figshare page_:

> This database is not designed for research as it intentionally removes some of the real-world complexities. The original database is published at Ecological Archives(http://esapubs.org/archive/ecol/E090/118/) and this version of the database should be used for research purposes. The Python code used for converting the original database to this teach version is included as 'create_portal_teach_dataset.py'. **Suggested changes or additions to this dataset can be requested or contributed in the project GitHub repository(https://github.com/weecology/portal-teachingdb).**

[emphasis added]

Zip archive is just a an archive of the master branch of that Git repo. My understanding is that Figshare is occasionally synchronized with the Git repo. So, in a sense, we should treat links to that Git repository and Figshare equivalently.

As a quick-fix we can add `survey2001.csv` and `survey2002.csv` to the setup page with links to these files in our `/data` directory.

Also, on the setup page we should change the wording to emphasize the fact that these three files are not in the zip archive nor can they be found on Figshare...

I think we should make the lesson self-consistent: it shouldn't rely on "external" resources.

**Comment by jensentobias** [comment]
Ok. From your feedback it seems that you will be interested in a PR where survey2001.csv and survey2002.csv are added as links on the setup episode, emphasizing that not all data are available via Figshare nor the zip archive. Later we could work on making the lesson self-consistent.

If you agree, and will prepare a PR.

**Comment by maxim-belkin** [comment]
Yes.

**Comment by martinosorb** [comment]
Hi, is this dormant? I have encountered this problem while preparing to teach.

**Comment by maxim-belkin** [comment]
I believe this issue has been resolved in #462.
