### ISSUE TITLE
Ep8: Issue when using numpy

### ISSUE THREAD

**Issue by Benfeitas** [datacarpentry/python-ecology-lesson#411]
In [episode 8](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/_episodes/08-putting-it-all-together.md), `numpy` is imported as `import numpy` but then the `beta` distribution calls it with `np`. So it raises the import error for `np`.

`beta_draws = np.random.beta(a, b)`

Either `import numpy as np` and fix other lines where it is used; or fix `beta_draws = numpy.random.beta(a, b)`.

**Comment by wrightaprilm** [comment]
I caught this after teaching last month, and then forgot to fix it. I'll sort that out now.

Thanks!
