### ISSUE TITLE
Ordered items in dictionary? 

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/python-ecology-lesson#425]
The episode [Short Introduction to Programming in Python](https://datacarpentry.org/python-ecology-lesson/01-short-introduction-to-Python/index.html) notes in the key points at the end:

> Dictionaries are unordered data structures that provide mappings between keys and values.

However it is not actually noted in the lesson whether dictionaries are ordered.  Also, as of Python 3.7, a dictionary's ordering is preserved (https://docs.python.org/3/library/collections.html).

**Comment by maxim-belkin** [comment]
Thank you, Maneesha. This discussion resurfaces from time to time. I think it would be best to remove the word "unordered" here. What do you think?

**Comment by maneesha** [comment]
Yes, that sounds good!

**Comment by maxim-belkin** [comment]
This issue has been addressed in #433
