### ISSUE TITLE
Reminder that plotnine is not part of Anaconda

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/python-ecology-lesson#426]
In the [Making Plots With plotnine](https://datacarpentry.org/python-ecology-lesson/07-visualization-ggplot-python/index.html) lesson, there is a disclaimer that shows how to load `plotnine`.

I would recommend also mentioning here a reminder that `plotnine` is not in the standard Anaconda package and needs to be installed separately.

**Comment by maxim-belkin** [comment]
We do mention it and explain how to install it on the Setup page:
https://datacarpentry.org/python-ecology-lesson/setup.html#download-plotting-package

> The plotting package plotnine is not installed by default.  From the terminal, type:
> ```
> conda install -c conda-forge plotnine
> ```

Nonetheless, it wouldn't hurt to remind learners that they have to install `plotnine` manually. I'm marking this issue as "good first issue" and "help wanted". Thanks, Maneesha!

**Comment by mathewsarath** [comment]
This issue is solved.

**Comment by maxim-belkin** [comment]
Thanks for the ping, @mathewsarath! :)
