### ISSUE TITLE
Ordering of left/right does not matter for *any* join

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/python-ecology-lesson#429]
The [Combining DataFrames with Pandas](https://datacarpentry.org/python-ecology-lesson/05-merging-data/index.html) notes that:

>  For inner joins, the order of the left and right arguments does not matter.

However, this is true of all joins.  I would suggest modifying this text to reflect this.  Otherwise it is misleading and implies that it may matter for other types of joins.

**Comment by maxim-belkin** [comment]
I believe order matters for left and right (outer) joins. Could you please clarify your point?
