### ISSUE TITLE
Correctly link to other lessons when they are referenced

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/python-ecology-lesson#436]
In the [indexing and slicing lesson](https://datacarpentry.org/python-ecology-lesson/03-index-slice-subset/index.html), there is a place where it says

> Note that the weight column of our DataFrame contains many null or NaN values. We will explore ways of dealing with this in Lesson 03.

Generally speaking, if other lessons are referenced, these should be linked to, so that it is easier to quickly navigate to that lesson.

Also, in this case, it is [lesson 4](https://datacarpentry.org/python-ecology-lesson/04-data-types-and-format/index.html) that introduces concepts of null data values, not lesson 3.

**Comment by maxim-belkin** [comment]
Thanks, Maneesha. Your're correct -- we should definitely link to the next episode. Moreover, we should also fix the wording: here, we're talking about Lesson **episode**, not Lesson itself.

I'm marking this as "Good first issue" and "help wanted"

Thanks for spotting this.

**Comment by Isaac-Jones** [comment]
I believe this fixed the issue. Also, this is my first time so I'm not sure if you prefer to get a link here or not. https://github.com/datacarpentry/python-ecology-lesson/pull/481

**Comment by maxim-belkin** [comment]
Thank you, @Isaac-Jones! I'll review your PR in a little bit.
