### ISSUE TITLE
Why not use surveys_df['year'].unique() rather than range()

### ISSUE THREAD

**Issue by mboisson** [datacarpentry/python-ecology-lesson#44]
In the lesson about automation, why not pull the list of unique years from surveys_df['year'].unique() rather than creating confusion with the range() function ?

It would simplify the lesson quite a bit.

**Comment by itcarroll** [comment]
I believe @qjcg meant to close this issue with pull request #78.

**Comment by tracykteal** [comment]
It has been addressed, so I'll close this.
