### ISSUE TITLE
Update markdown processor to kramdown

### ISSUE THREAD

**Issue by qjcg** [datacarpentry/python-ecology-lesson#45]
The [`redcarpet`](https://github.com/vmg/redcarpet) markdown processor used (i.e. in `_config.yml`) to convert our `.md` files to HTML via GitHub Pages / Jekyll will **[no longer be supported] as of May 1st 2016**.

Though the above states that:

> If you're currently using Markdown processors that support GitHub-flavored Markdown, such as Rdiscount or Redcarpet, then you don't need to change your Markdown files for them to render properly.

this does *not* appear to be completely accurate in practice.

Thus, the processor must be changed in `_config.yml` (to [Kramdown](http://kramdown.gettalong.org/index.html), the markdown processor to be used going forward), and the rendered content should be reviewed for errors (i.e. does it look OK?) at the same time.

[no longer be supported]: https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/

**Comment by qjcg** [comment]
Initial work pushed to redcarpet-to-kramdown branch (a6bf1b035b7b758f80efa7ca61df505d0c93089b, f372f0dfdcd95eaf535731aa6943880fb09989f9).

**Comment by justbennet** [comment]
@qjcg I tried changing the markdown processor to kramdown in a clone by simply modifying the _config.yml, and it appears to make the background color for code samples pink now...?

http://justbennet.github.io/python-ecology-lesson/01-starting-with-data

Let me know if I can help with this.  I can put some time into the python-ecology-lesson.

**Comment by qjcg** [comment]
Hi @justbennet, glad to have you on board!

Yes, it looks like the issue is that we/GitHub are switching from away from redcarpet with [pygments](http://pygments.org/) for syntax hilighting to kramdown with [rouge](http://rouge.jneen.net/) for syntax hilighting. For example, one GitHub Pages user has described some potential issues related to the transition [here](http://idratherbewriting.com/2016/02/21/bug-with-kramdown-and-rouge-with-github-pages/).

As mentioned earlier in this issue, I've been working in the [redcarpet-to-kramdown](https://github.com/datacarpentry/python-ecology-lesson/tree/redcarpet-to-kramdown) branch [1] to get the "migration" started, and like you I've noticed that the background of code blocks is pink, which is a little jarring.

I'd be very happy to have you assist in cleaning this up. The place to start would be looking at:

- [header.html](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/_includes/header.html), which links to the CSS files used for styling
    - notably, Pygments' [friendly.css](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/css/pygments/friendly.css) is still being linked to...

The end goal is code blocks with syntax hilighting that integrates nicely with the surrounding text. Pull requests regarding this (or any other) issue are very welcome, and your offer of spending some time on this lesson is appreciated! If you have any questions please don't hesitate to ask.

[1]: If you're not familiar with git's branch and merge workflow, there's a good primer [here](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging). In any case, no detailed knowledge of branching/merging is necessary to contribute --- all pull requests will be considered.

**Comment by carpenterbennet** [comment]
@qjcg I think I now know a bit more about branching and pull requests on GitHub now than yesterday.  I just summarized my mistakes in the README.md at https://github.com/carpenterbennet/topic_branching and if you have a few minutes and care to take quick look for anything I've said that's plain wrong, I would appreciate it.  I'm hoping that might be useful to someone.

I'll see if I can track down the pink....  Let you know when if I make any progress.

**Comment by justbennet** [comment]
@qjcg Sorry about that, was logged into the example acccount.  That last comment was my doppelganger.

**Comment by qjcg** [comment]
No problem @justbennet. I'll have a quick look over your branching document, but that conversation should move over there. Let's keep the discussion here focused on the kramdown/rouge transition.

**Comment by justbennet** [comment]
Yep.  You asked about what I know, and that's what it is.  ;-)

**Comment by justbennet** [comment]
This text

/* Highlighted changes in code. */
.highlight {
    background-color: mistyrose;
}

from .../css/lesson.css seems to be the source of the pink background in code blocks.

**Comment by justbennet** [comment]
Rouge appears to be marking code blocks thusly, which is what's calling it out, I think:

<div class="highlighter-rouge"><pre class="highlight">
   <code>
      <span class="kn">import</span> <span class="nn">pandas</span> 
      <span class="kn">as</span> <span class="nn">pd</span>
   </code>
</pre></div>

**Comment by justbennet** [comment]
Does this look better?
http://justbennet.github.io/kramdown-test/01-starting-with-data

**Comment by qjcg** [comment]
Yep, the syntax highlighting looks great! Please send along a PR (against the gh-pages branch) when you're ready.

**Comment by justbennet** [comment]
I think that style might have got introduced into the lesson.css file for a reason.  My suspicion is that it is used somewhere to highlight errors in code fragments or something.  I changed both the lesson.css and in _config.yml.  I will probably poke around to see if I can see where it was used under the old scheme so I can tell people what to look for (and maybe how to change it) to retain the current tag function.

Should I make the pull request against your branch for the conversion?  I'm not sure I know how to do that.

**Comment by qjcg** [comment]
Sounds good. As mentioned in my last message, please make your PR against the gh-pages branch.

**Comment by justbennet** [comment]
I submitted the PR.

**Comment by qjcg** [comment]
Thanks @justbennet, looks like your PR #51 plus commit [c03fc](https://github.com/datacarpentry/python-ecology-lesson/commit/c03fcfb475158c249c5292457557b32fa9b85446) have resolved this! Closing.
