### ISSUE TITLE
Broken links in contributing.md

### ISSUE THREAD

**Issue by nettic** [datacarpentry/python-ecology-lesson#450]
The contributing.md file has at least 3 broken links. Link to file:
https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/CONTRIBUTING.md

The 3 links are in the section "What to contribute".
"or you may also look at the issues for **Data Carpentry**, **Software Carpentry**, and **Library Carpentry** projects." (broken links are bold).

Wrong links:
Data Carpentry: https://github.com/issues?q=user%3Adatacarpentry
Software Carpentry: https://github.com/issues?q=user%3Aswcarpentry
Library Carpentry: https://github.com/issues?q=user%3Alibrarycarpentry

Corrected links:
Data Carpentry: https://github.com/search?q=user%3Adatacarpentry
Software Carpentry: https://github.com/search?q=user%3Asoftwarecarpentry
Library Carpentry: https://github.com/search?q=user%3Alibrarycarpentry

Cheers
Sebastian

**Comment by maxim-belkin** [comment]
Hi Sebastian,

I'm not positive the links you list above are broken - they bring me to proper locations when I click on them. Why do you think they're broken?

Maxim

**Comment by nettic** [comment]
Unfortunately, still for me they are broken. See screenshot in a pdf:
[Page not found GitHub.pdf](https://github.com/datacarpentry/python-ecology-lesson/files/4215774/Page.not.found.GitHub.pdf)

**Comment by maxim-belkin** [comment]
Does https://github.com/issues work for you?

**Comment by nettic** [comment]
Yes. It shows me my issues (this issue).

**Comment by maxim-belkin** [comment]
Could you please try replacing the text in the search box with `user:datacarpentry` and report the full URL you end up at?

**Comment by nettic** [comment]
This is my URL: https://github.com/issues?utf8=✓&q=user%3Adatacarpentry

**Comment by nettic** [comment]
The following works fine, too: https://github.com/issues?q=user%3Adatacarpentry

**Comment by maxim-belkin** [comment]
> This is my URL: [https://github.com/issues?utf8=✓&q=user%3Adatacarpentry](https://github.com/issues?utf8=%E2%9C%93&q=user%3Adatacarpentry)

Good, this is the URL I end up on too.

So, I'm a bit confused. Do links work for you or not? Previously you said:

> Wrong links:
> Data Carpentry: https://github.com/issues?q=user%3Adatacarpentry

And now:

> The following works fine, too: https://github.com/issues?q=user%3Adatacarpentry

These two links seem identical to me.

**Comment by nettic** [comment]
Now, it is working for me, too......:-0
I am confused. Sorry!

**Comment by nettic** [comment]
I realized, that this error occurs, when I am in a private tab and click the links with opening in a second private tab!

**Comment by maxim-belkin** [comment]
> I realized, that this error occurs, when I am in a private tab and click the links with opening in a second private tab!

Ah, I see! Yes, one has to be logged in to GitHub to use https://github.com/issues.

Consider raising this issue in the [carpentries/styles](https://github.com/carpentries/styles) repository -- this is where all The Carpentries lessons get CONTRIBUTING.md from. Perhaps, we should add a sentence or two explaining that one has to be logged in (to GitHub) and not in Private browsing mode to use these links.

Thank you for the report anyway! Things like these links can change in the future so it's always a good idea to make sure that they work.
