### ISSUE TITLE
03-index-slice-subset.md: wrong operator shown in Objectives (`=` instead of `==`)

### ISSUE THREAD

**Issue by snownontrace** [datacarpentry/python-ecology-lesson#454]
The 7th item of the Objectives of this lesson (https://datacarpentry.org/python-ecology-lesson/03-index-slice-subset/) states:

"Query / select a subset of data using a set of criteria using the following operators: =, !=, >, <, >=, <=."

The first operator should be "==" rather than "=."

**Comment by maxim-belkin** [comment]
Yes, you're correct, Shaohe. Would you be willing to submit a PR to fix that?

**Comment by snownontrace** [comment]
Yes! Plus a couple of additional typos I spotted. Will do some time in this
week.

Best,
Shaohe

**Comment by maxim-belkin** [comment]
Awesome, thank you!
