### ISSUE TITLE
Setup instructions for python require knowledge of bash

### ISSUE THREAD

**Issue by ppxasjsm** [datacarpentry/python-ecology-lesson#457]
I believe there is some plan on improving the setup instructions, but I am relatively new to all of this and not really in the know. It seems that the datacarpentry setup instructions for python essentially required knowledge of bash, which is not a given and often confusing at the start.

This may have been discussed elsewhere and though of already (e.g. in issue #276), but would it make sense as an interim to use the softwarecarpentry instructions at least for the python part also for the datacarpentry ones?
I found the the softwarecarpentry ones to be easy to follow for a novice, particularly on windows not having encountered a command line before. 

Any thoughts on this?

**Comment by maxim-belkin** [comment]
Hi Toni. Thank you for bringing this up!

> Any thoughts on this?

We're always open to suggestions!

> This may have been discussed elsewhere and though of already (e.g. in issue #276), but would it make sense as an interim to use the softwarecarpentry instructions at least for the python part also for the datacarpentry ones?

Which SWC Python lesson do you suggest we use as an example? [Python Novice Inflammation][pni] or [Python Novice Gapminder][png]?

Would you like to work on this change?

[pni]: https://github.com/swcarpentry/python-novice-inflammation
[png]: https://github.com/swcarpentry/python-novice-gapminder

**Comment by ppxasjsm** [comment]
I'd be happy to implement the change.

**Comment by maxim-belkin** [comment]
> I'd be happy to implement the change.

That'd be great, thank you!

Side note: the commit that got linked to this issue (titled "includes/links.md: Update PyYAML link") has nothing to do with it. It comes from the carpentries/styles repository which all lessons have to periodically sync with.

**Comment by k-rns** [comment]
In addition to this issue, the interpreter part of this episode [Short Introduction to Programming in Python](https://datacarpentry.org/python-ecology-lesson/01-short-introduction-to-Python/index.html)  also has a few bash commands, which I found a bit confusing when learning the episode. When installing python with anaconda I could only do this in the anaconda prompt, not the command prompt. 

I`m also new to this, so I`m not sure if this is the best location to put this comment.

**Comment by maxim-belkin** [comment]
Hi Karen,

Yes, this is a good place to put this comment. I guess you're talking about the very beginning of said episode where it says `To start Python in this mode, execute python...`.  I believe that this bit is indeed OS-specific. Aside from changing the narrative, we've got some tools to provide OS-specific instructions but they're very clumsy and require injections of HTML -- see, for example https://carpentries.github.io/workshop-template/#python. We can attempt to improve these tools but that change will take some time and, in the meantime, we can update that section of the lesson. Would you like to do that?

**Comment by ppxasjsm** [comment]
Finally made a pull request, sorry for being so slow about this.

**Comment by btovar** [comment]
Fixed by #470
