### ISSUE TITLE
Lesson refers to data types from R

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/python-ecology-lesson#486]
The [Starting With Data lesson](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/_episodes/02-starting-with-data.md) refers to data types like characters and factors which are not in Python.  I'm guessing this is a carryover from the R lessons. 

`A DataFrame is a 2-dimensional data structure that can store data of different types (including characters, integers, floating point values, factors and more) in columns. It is similar to a spreadsheet or an SQL table or the data.frame in R. A DataFrame always has an index (0-based). An index refers to the position of an element in the data structure.`

**Comment by btovar** [comment]
@maneesha Thanks for your report! Updated to categories, which is what pandas uses.
