### ISSUE TITLE
Contributing MD page is dated

### ISSUE THREAD

**Issue by lwasser** [datacarpentry/python-ecology-lesson#5]
The contributing document reflects ALL DC lessons. Should we change it to reflect only python materials? And if so, was @qjcg and @fmichonneau 's workshop the first DC python workshop and our SEA one the second? And 2) who else has contributed to these Python materials? 

I've got:
Ethan White, ??, Mariela Perignon, John Gossett, Francois Michonneau, Leah Wasser, ...

i will be submitting a new PR soon with edits to L08 - SQL and Python and a few other edits throughout.
Thank you!

**Comment by ethanwhite** [comment]
> Should we change it to reflect only python materials?

Yep.

**Comment by qjcg** [comment]
Closing, as CONTRIBUTORS.md now appears up to date.
