### ISSUE TITLE
ep3 feedback

### ISSUE THREAD

**Issue by TrungNg** [datacarpentry/python-ecology-lesson#501]
<strong>Feedback on ep3</strong>

- pandas.read_csv is mostly used and could be introduced more with its options, e.g. index_col and header. An option of "index_col=0" could be useful here.
If space is a problem, the part of (first) reading and then assigning the read data frame to a variable can be combined into one cell: 
> surveys_df = pd.read_csv("data/surveys.csv") 
> surveys_df

- The output of the first read_csv looks like the index was described but not shown on the Output (probably on purpose). This may be confusing to readers.

Thanks!

**Comment by btovar** [comment]
@TrungNg Thanks for your feedback. I think we want to keep the introduction of `read_csv` as simple as possible to minimize the new concepts a reader has to understand.
