### ISSUE TITLE
Lesson Contribution: Warning about Word Processors

### ISSUE THREAD

**Issue by SalazarDomingo** [datacarpentry/python-ecology-lesson#527]
Small lesson contribution to:
Short Introduction to Python
Data Analysis and Visualisation in Python
https://datacarpentry.org/python-ecology-lesson/01-short-introduction-to-Python/index.html

Short paragraph to be added before displaying the script example.py:

Any text processor may be used to write scripts (like Notepad++ in Windows and Nano/Vim/Emacs in Linux and MacOS) but no word processors like MS Word because they may introduce invisible control characters that will confuse Python.

**Comment by btovar** [comment]
@SalazarDomingo Thank you for your suggestion. I submitted a pr to make the clarification.
