### ISSUE TITLE
locate `_include/scripts`

### ISSUE THREAD

**Issue by goi42** [datacarpentry/python-ecology-lesson#528]
The [Instructor Notes](https://datacarpentry.org/python-ecology-lesson/guide/) for [Data Analysis and Visualization in Python for Ecologists](https://datacarpentry.org/python-ecology-lesson/index.html) refers to something called "the `_include/scripts` directory". What is this? I do not find it mentioned on the [setup page](https://datacarpentry.org/python-ecology-lesson/setup.html) or in the [zipped files](https://datacarpentry.org/python-ecology-lesson/data/portal-teachingdb-master.zip).

**Comment by tobyhodges** [comment]
Thanks for raising this, @goi42. The directory is located [in this lesson repository](https://github.com/datacarpentry/python-ecology-lesson/tree/gh-pages/_includes/scripts). If you would like to open a PR to link to its location on GitHub from the Instructor Notes page, I would be delighted to review it.

**Comment by btovar** [comment]
Fixed in #530
