### ISSUE TITLE
Switch plotnine with seaborn and add statannotations

### ISSUE THREAD

**Issue by callaband** [datacarpentry/python-ecology-lesson#562]
From my perspective, plotnine is great for learners who are switching from R to python. 

However, if new to python and just learning a plotting program, seaborn seems to be a lot more intuitive and has detailed documentation and plenty of examples and help available online. Seaborn also pairs much better with Matplotlib. 

[The Python Graph Gallery](https://www.python-graph-gallery.com/) is great resource that gives examples of seaborn and matplotlib plots and code that would be useful for learners. 

In addition, one of the many things people are interested in is applying statistics to their data, such as using [statannotations](https://github.com/trevismd/statannotations), is based on using seaborn graphs. This could be really useful and of interest to learners. 

If this is of interest, I would be happy to contribute.

**Comment by btovar** [comment]
@callaband Hi Celeste, thank you making this suggestion, Thank you for offering to contribute!  In a general setting I agree with you, and it has been a little hard to decide which plotting package to use. However, the tipping point is that people in the ecology community are more familiar with grammars of graphics, thus plotnine makes more sense in this particular case.

For a previous discussion on this you can check https://github.com/datacarpentry/python-ecology-lesson/issues/406
