### ISSUE TITLE
Depreciated default setting gives error with pandas>=2.0.1

### ISSUE THREAD

**Issue by catchSheep** [datacarpentry/python-ecology-lesson#564]
In `episodes/02-starting-with-data.md` line [519](https://github.com/datacarpentry/python-ecology-lesson/blob/main/episodes/02-starting-with-data.md?plain=1#LL519C20-L519C20) no longer produces the expected output in pandas>=2, and instead produces a very long error as it tried to take the mean of the non-numeric columns (eg species code, gender etc)

In pandas version 1.5.3 we get a future warning indicating that it will no longer work:
![Screenshot from 2023-05-26 08-59-04](https://github.com/datacarpentry/python-ecology-lesson/assets/81134674/9359ed6f-bd55-4ce3-ae60-8d4fbd01d6e7)

This can be fixed by just passing in `numeric_only=True` to `grouped_data.mean()`, e.g.:
```py
grouped_data.mean(numeric_only=True)
```
![Screenshot from 2023-05-26 09-02-09](https://github.com/datacarpentry/python-ecology-lesson/assets/81134674/cd9e8a87-efc2-463a-8f40-1cd15bcb733c)

**Comment by btovar** [comment]
@catchSheep Thanks for your report! Would you like to submit a pr to fix the issue?

**Comment by catchSheep** [comment]
No worries, I just made made one: https://github.com/datacarpentry/python-ecology-lesson/pull/565
I ended up finding three values needing to be changed in this episode, included in that commit

**Comment by btovar** [comment]
Fixed by #565
