### ISSUE TITLE
Anaconda may not be easy for everyone 

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/python-ecology-lesson#569]
The [ecology lesson](https://datacarpentry.org/python-ecology-lesson/00-before-we-start.html#knowing-your-way-around-anaconda) says that Anaconda "makes it easy to install and update additional packages."  
It may not be easy for everyone and I would recommend changing this language.

**Comment by btovar** [comment]
@maneesha what about:   ... also comes with a package manager called conda that is used to install and update additional packages.

**Comment by maneesha** [comment]
That sounds good. I have no strong preferences about the exact language to use here; only that we should not refer to managing packages as an easy task in any context.
