### ISSUE TITLE
Invalid indexing statement in text block

### ISSUE THREAD

**Issue by phofl** [datacarpentry/python-ecology-lesson#579]
### What is the problem?

The statement here

https://github.com/datacarpentry/python-ecology-lesson/blob/870bd311f73278310d4cc09f6d61eaf54815ed64/episodes/03-index-slice-subset.md?plain=1#L393

is invalid, it needs a a second set of brackets

### Location of problem (optional)

https://github.com/datacarpentry/python-ecology-lesson/blob/870bd311f73278310d4cc09f6d61eaf54815ed64/episodes/03-index-slice-subset.md?plain=1#L393

**Comment by btovar** [comment]
@phofl thanks you for your report, and for submitting the fix!
