### ISSUE TITLE
Trainer checkout

### ISSUE THREAD

**Issue by wrightaprilm** [datacarpentry/python-ecology-lesson#60]
What are responsibilities @qjcg and I have when users submit trainer checkout exercises? Do we just merge these as we see fit, or do we need to tag you in/do something else, @tracykteal @gvwilson?

**Comment by gvwilson** [comment]
Please drop me an email (in case the trainee didn't) and then treat as 
any other change request.
Thanks,
Greg

**Comment by wrightaprilm** [comment]
OK, since I have you here right now, and Tracy has already been pinged and will look: https://github.com/datacarpentry/python-ecology-lesson/pull/59

I'll close this.

**Comment by tracykteal** [comment]
Yes, just merge if it is appropriate and useful. Either way though, let @gvwilson know that the person has submitted the exercise. We're currently revisiting this process, so will keep you posted.
