### ISSUE TITLE
Clarification about using a "terminal" or "anaconda prompt" 

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/python-ecology-lesson#605]
### How could the content be improved?

In the [summary and setup section](https://datacarpentry.org/python-ecology-lesson/#required-python-packages) when it comes to installing plotnine, we say to use the Anaconda prompt if on Mac or Linux and a terminal if on Windows.  Late, to launch a Jupyter notebook, we say to use the terminal (not anaconda prompt).  I don't use Windows and Mac enough to know if this distinction is important and makes a difference.  In either case, we should probably be consistent about what we recommend.

**Comment by quist00** [comment]
The windows CMD or PowerShell in most cases won't know the path to find Anaconda related commands by default.  The Anaconda prompt is a CMD shell with path settings built in to eliminate the need to have users manipulate their OS path settings. I don't have a windows machine handy to test if Jupyter won't be found by default either, but I don't see any harm in having them use the Anaconda prompt regardless.

**Comment by quist00** [comment]
Well after testing on my home windows machine, Jupyter opens from cmd, gitbash, powershell, and Anaconda prompt, so I think I will just adjust it to be terminal or Anaconda Prompt.
