### ISSUE TITLE
Notebooks can be in "command" or "edit" mode

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/python-ecology-lesson#611]
### How could the content be improved?

In the section on [Notebook modes: Control and Edit](https://datacarpentry.org/python-ecology-lesson/jupyter_notebooks.html#notebook-modes-control-and-edit), it says notebooks can be in "control" or "edit" mode.  According to the [Jupyter notebook documentation](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Notebook%20Basics.html#Modal-editor), this should be "command" or "edit" mode.

### Which part of the content does your suggestion apply to?

https://datacarpentry.org/python-ecology-lesson/jupyter_notebooks.html#notebook-modes-control-and-edit

**Comment by quist00** [comment]
Thanks for taking the time to submit this catch.
