### ISSUE TITLE
Revise learning objectives using Bloom's Taxonomy

### ISSUE THREAD

**Issue by qjcg** [datacarpentry/python-ecology-lesson#65]
Following the discussion in PR #63, we will pilot rewriting our lesson objectives with reference to [Bloom's Taxonomy](https://en.wikipedia.org/wiki/Bloom's_taxonomy).

To start, we will aim to follow the two-level grouping of objectives [suggested](https://github.com/datacarpentry/python-ecology-lesson/pull/63#issuecomment-222006439) by @ErinBecker.

PRs with revised objectives should be made against the [new-learning-objectives branch](https://github.com/datacarpentry/python-ecology-lesson/tree/new-learning-objectives) of this repo.

**Comment by tracykteal** [comment]
@kariljordan @ErinBecker I think this is done for these lessons now?
