### ISSUE TITLE
Add instructor notes document for this lesson

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/python-ecology-lesson#67]
I'm working on helping direct instructor attention towards fixing up/contributing to instructor notes. Currently don't have a link to provide for instructor notes for this lesson. Please add - even a blank document would be somewhere to point towards.

**Comment by qjcg** [comment]
Hey Erin, please feel free to reference the (currently empty) [INSTRUCTORS.md](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/INSTRUCTORS.md) as the place to put instructor notes for this lesson. 

If there's anything else you need, please don't hesitate!

**Comment by ErinBecker** [comment]
Thanks John!

On Tue, May 31, 2016 at 4:42 PM, John Gosset <notifications@github.com>
wrote:

> Hey Erin, please feel free to reference the (currently empty)
> INSTRUCTORS.md
> <https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/INSTRUCTORS.md>
> as the place to put instructor notes for this lesson.
>
> If there's anything else you need, please don't hesitate!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/datacarpentry/python-ecology-lesson/issues/67#issuecomment-222853508>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASSbfxROaJSVnIdys_nm97m_RXwCtF4Xks5qHMdLgaJpZM4Iq_8O>
> .
>



-- 
*Erin Becker*, PhD
Data Carpentry, Associate Director
http://www.datacarpentry.org/
Research Associate, MMG Dept., UC Davis
