### ISSUE TITLE
Standardize on a single code style throughout the module

### ISSUE THREAD

**Issue by jdidion** [datacarpentry/python-ecology-lesson#71]
There are specific DC modules where coding style is discussed (e.g. http://www.datacarpentry.org/semester-biology/materials/style/), but it is largely ignored by most modules. I don't find this particularly concerning as there is a lot to cover and style is typically not first on the list. However, I don think that one of the ways (perhaps the best way) of learning to code is to read other peoples' code. And one of the hallmarks of well-written code is consistent style. Thus, I think it's important to adopt a single coding style, at least within a module if not across all DC modules. As an example, in the "Introduction to Python" module, two different ways of naming variables appear in the same code block:

```
# tuples use paratheses
ATuple= (1,2,3)
anotherTuple = ('blue','green','red')
# notes lists uses square brackets
AList = [1,2,3]
```

This is unnecessarily confusing to novices. Since there are lots of religious wars regarding "proper" style, I think the default should be to adopt PEP8 unless someone has a very good reason to do otherwise. So the above code block should be changed to:

```
# tuples use paratheses
a_tuple = (1,2,3)
another_tuple = ('blue', 'green', 'red')
# notes lists uses square brackets
a_list = [1,2,3]
```

My specific proposals are:
1. This DC module (and hopefully all others) should settle on a single coding style that should be specifically stated in the module's meta-information.
2. All modules should be reviewed to ensure that they conform to style. This could probably be automated using something like https://pypi.python.org/pypi/autopep8.

**Comment by mkuzak** [comment]
Fixed by #131
