### ISSUE TITLE
Should the "Starting with Data" lesson mention Pandas Series explicitly?

### ISSUE THREAD

**Issue by bobtodd** [datacarpentry/python-ecology-lesson#80]
When I was working through the "Starting with Data" lesson, I noticed the "Summary Plotting Challenge" starts with the `dict`

``` python
d = {'one' : pd.Series([1., 2., 3.], index=['a', 'b', 'c']),'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}
```

As far as I can see, the lesson nowhere mentions the `pd.Series` type.  For the learner the above line of code might appear pretty opaque.

In addition, under "Manipulating Our Species Survey Data", the lesson early teaches the learner to check types:

``` python
type(surveys_df)
# output: pandas.core.frame.DataFrame
```

But this otherwise good practice could run into trouble later with the `species_counts`:

``` python
type(species_counts)
# output: pandas.core.series.Series
```

Perhaps this could this be fixed by an early introduction to the Series terminology.  For example, just before introducing the Pandas DataFrame, the lesson could say something like the following.

> You can imagine a Pandas **Series** as a single column of a spreadsheet: a list of data, perhaps of different types, collected together and put in some order.  A Pandas **DataFrame** is akin to the full spreadsheet: a collection of data in several columns -- i.e. in several Pandas **Series** -- stacked next to one another to make a 2-dimensional array.

The lesson could potentially continue as-is from there, maybe just highlighting at some point (perhaps in the `species_counts` example) that pulling out a single row gives a Series in Pandas terminology.

**Comment by MichaelConnell** [comment]
> You can imagine a Pandas Series as a single column of a spreadsheet: a list of data, perhaps of different types, collected together and put in some order. A Pandas DataFrame is akin to the full spreadsheet: a collection of data in several columns -- i.e. in several Pandas Series -- stacked next to one another to make a 2-dimensional array.

Correction: A Series is like a NumPy array in that it can only contain homogeneous data.  If you select a row from a DataFrame and it has multiple types, they will all be cast up to the single type that accommodates them all (which is usually 'object' - if there are any strings or categories).

> The lesson could potentially continue as-is from there, maybe just highlighting at some point (perhaps in the species_counts example) that pulling out a single row gives a Series in Pandas terminology.

This is true that pulling out a single row gives a Series.  Pedagogically, though, it would be preferable to point out that pulling out a single *column* gives you a Series since onceptually, a DataFrame can be thought of as a dictionary of Series (which are the columns), so pulling out one column gives you back a Series preserving its original dtype.

**Comment by bobtodd** [comment]
Thanks for the correction, @MichaelConnell.  Sorry, in the second snippet you quoted, I should've written "column" instead of "row".  And in the first snippet, I hadn't thought about the necessity for a uniform data type.  You're totally right.  And the "dictionary of Series" perspective is a great one... thanks!

Overall, my focus was on making sure that the lesson as a whole gives the reader a framework for understanding the statements and output of later exercises.  I'm open to different phrasing or analogies, and especially to corrections of any misstatements.

**Comment by wrightaprilm** [comment]
I missed this issue opening while I was traveling over the summer. You're right that we should explicitly address the meaning of a series. It looks like you're pretty close on having a functional definition of Series, then nesting that with DataFrame. 

> You can imagine a Pandas Series as a single column of a spreadsheet: a list of data, of the same type, collected together and put in some order. A Pandas DataFrame is akin to the full spreadsheet: a collection of data in several columns -- i.e. in several Pandas Series -- stacked next to one another to make a 2-dimensional array. If you recall our spreadsheets lesson from this morning, a Series is like a column in a spreadsheet, with the DataFrame being equivalent to the whole sheet.


Or similar. So go ahead and make any last edits to the language, then open your pull request.

**Comment by willingc** [comment]
@wrightaprilm @tracykteal Let's go ahead and close this issue. [Lesson 1 on Starting with Data](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/_episodes/01-starting-with-data.md) now focuses on pandas so the original issue no longer pertains.

**Comment by wrightaprilm** [comment]
Agreed.
