### ISSUE TITLE
Lessons 00/01 getting a little overfull

### ISSUE THREAD

**Issue by wrightaprilm** [datacarpentry/python-ecology-lesson#81]
This round of instructor training, we had a lot of interest in the first two lessons in the Python set. Which is great! But also puts us in a position where we're looking a little overfull. So the first thing I want to know is if that's true. I think @qjcg has taught through this lesson recently? How did you find 00 and 01 went? Should we have a further discussion about streamlining these, or are we doing OK?

**Comment by tomhohenstein** [comment]
Hello!

Are you still looking into trimming lessons 00/01? I'm going through the  instructor training checklist and am willing to help. I also noticed that lesson 00 does not have learning objectives (I'd be happy to add that)

**Comment by wrightaprilm** [comment]
We are still interested in doing that, and would greatly appreciate the help. If you're interested in the issue to learning objectives, we have a separate branch for re-organizing them into Bloom's Taxonomy (suggested by @ErinBecker in #65). That's been a little stalled, for various reasons, but you're absolutely welcome to have a crack at it.

**Comment by wrightaprilm** [comment]
Since #169 is merged, I'm going to close this.
