### ISSUE TITLE
Check environment script

### ISSUE THREAD

**Issue by hugobowne** [datacarpentry/python-ecology-lesson#83]
Installation instructions were added as a result of #36 .

Would it be helpful to have a check environment script that people can run post-installation to confirm that they have it all in working order?

**Comment by wrightaprilm** [comment]
This would be fantastic. Are you interested in taking that on, and if so, do you want or need a partner?

**Comment by hugobowne** [comment]
I'm more than happy to take it on. I'll attempt it solo and let you know of any issues. Sound good?

**Comment by wrightaprilm** [comment]
Sorry for my late reply, sounds fine. Let me know if there's anything we can do to help.

**Comment by barrachri** [comment]
Hi Hugo, do you have any idea how to do this ?

**Comment by hugobowne** [comment]
@wrightaprilm  yes, I do. I'm currently writing a check_env.py and some instructions on running it to to include [here](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/_includes/setup.html). I plan to have something to you over the weekend

**Comment by hugobowne** [comment]
@wrightaprilm i plan to issue a PR with a check_env.py file. Can include it in a subdir here? https://github.com/datacarpentry/python-ecology-lesson/tree/gh-pages/_includes

Also, fine for me to add instructions on running it here? https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/_includes/setup.html

**Comment by hugobowne** [comment]
@wrightaprilm PR issued. As stated in [PR](https://github.com/datacarpentry/python-ecology-lesson/pull/90/), I have 

- added a check_env.py in dir _includes/scripts
- edited pythonSetup.html to give instructions on running it.

check_env.py checks, in the following order, whether:

- anaconda is installed as default;
- the system is running python3;
- ['numpy', 'matplotlib','pandas', 'jupyter'] are installed;

if any of these conditions are not satisfied, a meaningful AssertionError is thrown. Wrt #85, I think @barrachri has some great suggestions. I would suggest, however, that

- Full Anaconda distribution still be used as the cognitive overhead of workshop participants using `conda install` is higher than the computational/space overhead of installing full Anaconda;

FYI I have my work offsite beginning in a few hours so I may be AWOL this coming week! If so, I'll be right back into this after that

**Comment by hugobowne** [comment]
Oooooo I have now seen this [PR](https://github.com/datacarpentry/python-ecology-lesson/pull/89), in which @barrachri provides instructions for both Anaconda & miniconda. I like it!

**Comment by mkuzak** [comment]
@hugobowne can you confirm that the issue have been solved with your pull request #90 ?

**Comment by hugobowne** [comment]
@mkuzak confirmed, thanks.

**Comment by mkuzak** [comment]
@hugobowne thanks :)
