### ISSUE TITLE
Lack of requirements info, miniconda and how to lunch a Jupyter Notebook

### ISSUE THREAD

**Issue by barrachri** [datacarpentry/python-ecology-lesson#85]
I was checking the lesson as a part of the "Instructor Training Checkout".
- Adding a requirements page

I see that all the requirements part is handled by installing Anaconda.

I think could be important to add a requirements page where we explain which packages you need and some information about them instead of having all this information spread around the lecture. 
- Using miniconda

With Anaconda you are installing 300MBs libraries and we only use Python, Pandas and Matplotlib (Numpy is a requirement of Pandas).

Could be more useful to use Miniconda and give them a brief introduction how to install packages ?
- Lunch a Jupyter Notebook

I didn't find any info about how to lunch a jupyter notebook inside the lecture.

**Comment by wrightaprilm** [comment]
- Requirements Page

I'm not inherently opposed to adding a requirements page, but the Data Carpentry pages for all lessons (R, SQL, etc) all follow a style, in which you have the Requirements head, and then a subheader explaining the software requirements. In this case, Anaconda. If you'd like to make a pull request more detail, such as listing the specific packages under that subheader, that's fine.

- Using Miniconda

I think it could be useful, but the vast majority of Data Carpentry users either haven't programmed or have done so really minimally. In that context, we do try to keep the installations pretty simple. If you wanted to work up a draft of what this might look like, I'd be happy to look at it.

- Launch a Jupyter Notebook

If you want to go ahead and make a pull request adding that where you think it's reasonable (maybe as a check on the installation), that seems like a good idea.

Does that all sound reasonable, @barrachri (and my co-maintaner @qjcg)?

**Comment by gvwilson** [comment]
Once we switch to the new lesson template, there'll be a `setup.md` page for all of this - @barrachri, if you'd like to create a page with that name now submit a PR with some of these points in it, that would be a great start.

**Comment by barrachri** [comment]
So I will open 3 new issues:

* to add a new setup.md
* Use miniconda and install packages
* Launch a Jupyter notebook plus check installation

After I will open them I will close this one.

**Comment by wrightaprilm** [comment]
In re: bullet 3, Hugo Bowne is working on checking installs in #83. If you wouldn't mind working with him on whatever you had in mind for checking installation, that would be great.

For the miniconda stuff, why don't you put that straight into the new setup.md.  Since the template isn't 'live' yet, if we have some kinks to work out in terms of making miniconda seem accessible to new learners, we'll have a little time to work on that in a way that is separate from the working instructions included with the page build.

You don't need to open an issue for each PR, since we can have discussion on the PR itself. If you have reasons to want to open them as issues, though, do feel free to do that.

**Comment by qjcg** [comment]
Looks good to me @wrightaprilm, and thanks for proposing this @barrachri ! I'd agree with April that you don't necessarily need to open a corresponding issue for each PR.

**Comment by barrachri** [comment]
I created the PR for these 3 points :)

**Comment by mkuzak** [comment]
@barrachri I think this issue have been solved in your pull request #89 
if so, we can close this issue

**Comment by barrachri** [comment]
closed !
