### ISSUE TITLE
Broken Link: Setting Up Python

### ISSUE THREAD

**Issue by mjones01** [datacarpentry/python-ecology-lesson#93]
In the [Setting Up Python section](http://www.datacarpentry.org/python-ecology-lesson/#setting-up-python), where it says "Here you can find a python script check_env.py". 
The hyperlink to `check_env.py` is broken (http://www.datacarpentry.org/python-ecology-lesson/scripts/check_env.py).  

The file is now in _includes/scripts/ .

**Comment by wrightaprilm** [comment]
Accurate! Are you making a note of this as part of instructor training (i.e., declaring an intention to fix), or do you need me to tackle it?

**Comment by mjones01** [comment]
@wrightaprilm  Sorry for not being clear. I'm not sure the correct way to link to it now that it is in the _includes/ folder. I attempted to fix the link but was unsuccessful.  It would be wonderful if you would.

**Comment by wrightaprilm** [comment]
Oh, no problem, GitHub issues tracking is phenomenal, but when different audiences use it for different things, it can get a little hairy.

Anyway, it looks like it's a conflict between how the site builds and the directory layout of the materials. I'll get it figured out.

**Comment by wrightaprilm** [comment]
OK, so here's what I did on this:

I looked at the way we have this set up. Data Carpentry workshops don't necessarily do git, and learners haven't always executed a command line program, nor do they necessarily know how to navigate the directory structure. I think we've jumped in at too high a level on that page. So I moved the instructions for this into the instructors guide, and am leaving it up to the instructor for how to provide the script. Possible avenues:

- Having the learners do some cloning
- Having them download the repo as a zip
- Linking directly to the script from the workshop page
- Providing it via dropbox or similar

What do you think?

**Comment by mjones01** [comment]
I agree that it might be too high for some users and a direct link from a workshop page would probably work. As long as the script is mentioned in the INSTRUCTORS.md file (as it currently is) instructors will know that it is available.  This does however preclude users from checking for correct installation prior to a workshop.  Perhaps on the INSTRUCTOR.md file, you can add something like, "As an instructor you may consider adding a link to this script on the workshop page so that those users who are familiar with the command line can double check their installation prior to arriving at the workshop." 
I'll defer on the final decision to your experience.  I was actually using the lesson for self-learning to improve my skills with Python as I'm currently an R user & instructor.  There was some discussion a few weeks ago on the DISCUSS listserv about usability of the SC/DC lessons for individual/online learning. I don't see this change detracting from workshop learning but it does remove the resource for someone learning independently (although that isn't a Data/Software Carpentry focus).

**Comment by mkuzak** [comment]
We can also link to [raw version of the file](https://raw.githubusercontent.com/datacarpentry/python-ecology-lesson/gh-pages/_includes/scripts/check_env.py) on GitHub. This will make it easier to download.

**Comment by tracykteal** [comment]
Linking to the raw file is probably the best solution. It is a good idea to still have it there for self-guided learning as @mjones01 says. 

Adding a note that it's optional if you have access to a command line program is probably also useful.

**Comment by willingc** [comment]
I'll do a quick pr for this one.
