### ISSUE TITLE
Strings, integers and floats  and booleans

### ISSUE THREAD

**Issue by djinnome** [datacarpentry/python-ecology-lesson#97]
Hi folks,

   It is kind of a minor issue, but it might cause confusion in our students if we introduce 3 data types and then use a fourth in our [short introduction to python](https://github.com/datacarpentry/python-ecology-lesson/blob/gh-pages/00-short-introduction-to-Python.md).   Therefore, we might as well introduce the Boolean data type at the same time as we introduce Strings, integers, and floats.

**Comment by wrightaprilm** [comment]
Good catch. The trick here is that we introduce types before we introduce operators. I split the difference a bit and mentioned in the operators block that the return type of those statements is a bool. What do you think of that approach (the change is now pushed to 00, if you'd like to view)?

**Comment by djinnome** [comment]
Hi @wrightaprilm 

That works for me.  Thanks for the fix.
