### ISSUE TITLE
No images of plots in 06-plotting-with-matplotlib

### ISSUE THREAD

**Issue by jarmokivekas** [datacarpentry/python-ecology-lesson#99]
I noticed that lesson [06-plotting-with-matplotlib](http://www.datacarpentry.org/python-ecology-lesson/06-plotting-with-matplotlib) does not include any images of the plots that would be created by the various bits of example code. Is this a design decision, or have the images just not been created? I'd be willing to create python script that created example plot, and link those into the lesson's markdown.

**Comment by wrightaprilm** [comment]
Hi @jarmokivekas -

Closing this, as we've revamped the lesson. Thanks for participating in the discussion with us!
